apiVersion: v1
kind: Pod
metadata: 
  name: result-app-pod
  labes:
    name: result-app-pod
    app: demo-voting-app
spec: 
  containers:
    - name:  result-app
      image:  dockersamples/exampleresultapp_result
      ports:
      - containerPort:  80